using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AMSoftware.Crm.PowerShell.Commands
{
    internal static class HelpUrlConstants
    {
        public const string UseLanguageHelpUrl = "http://crmpowershell.amsoftware.nl/Use-CrmLanguage.html";
        public const string ConnectDeploymentHelpUrl = "http://crmpowershell.amsoftware.nl/Connect-CrmDeployment.html";
        public const string ConnectOrganizationHelpUrl = "http://crmpowershell.amsoftware.nl/Connect-CrmOrganization.html";
        public const string GetOrganizationHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmOrganization.html";
        public const string AddAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmAttribute.html";
        public const string AddBigIntAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmBigIntAttribute.html";
        public const string AddBooleanAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmBooleanAttribute.html";
        public const string AddDateTimeAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmDateTimeAttribute.html";
        public const string AddDecimalAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmDecimalAttribute.html";
        public const string AddDoubleAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmDoubleAttribute.html";
        public const string AddEntityKeyHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmEntityKey.html";
        public const string AddImageAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmImageAttribute.html";
        public const string AddIntegerAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmIntegerAttribute.html";
        public const string AddMemoAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmMemoAttribute.html";
        public const string AddMoneyAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmMoneyAttribute.html";
        public const string AddOptionSetAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmOptionSetAttribute.html";
        public const string AddRelationshipHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmRelationship.html";
        public const string AddStringAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmStringAttribute.html";
        public const string GetAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmAttribute.html";
        public const string GetEntityHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmEntity.html";
        public const string GetEntityKeyHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmEntityKey.html";
        public const string GetOptionSetHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmOptionSet.html";
        public const string GetRelationshipHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmRelationship.html";
        public const string NewEntityHelpUrl = "http://crmpowershell.amsoftware.nl/New-CrmEntity.html";
        public const string NewOptionSetHelpUrl = "http://crmpowershell.amsoftware.nl/New-CrmOptionSet.html";
        public const string NewOptionSetValueHelpUrl = "http://crmpowershell.amsoftware.nl/New-CrmOptionSetValue.html";
        public const string RemoveAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Remove-CrmAttribute.html";
        public const string RemoveEntityHelpUrl = "http://crmpowershell.amsoftware.nl/Remove-CrmEntity.html";
        public const string RemoveEntityKeyHelpUrl = "http://crmpowershell.amsoftware.nl/Remove-CrmEntityKey.html";
        public const string RemoveOptionSetHelpUrl = "http://crmpowershell.amsoftware.nl/Remove-CrmOptionSet.html";
        public const string RemoveOptionSetValueHelpUrl = "http://crmpowershell.amsoftware.nl/Remove-CrmOptionSetValue.html";
        public const string RemoveRelationshipHelpUrl = "http://crmpowershell.amsoftware.nl/Remove-CrmRelationship.html";
        public const string SetAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmAttribute.html";
        public const string SetBigIntAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmBigIntAttribute.html";
        public const string SetBooleanAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmBooleanAttribute.html";
        public const string SetDateTimeAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmDateTimeAttribute.html";
        public const string SetDecimalAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmDecimalAttribute.html";
        public const string SetDoubleAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmDoubleAttribute.html";
        public const string SetEntityHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmEntity.html";
        public const string SetImageAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmImageAttribute.html";
        public const string SetIntegerAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmIntegerAttribute.html";
        public const string SetMemoAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmMemoAttribute.html";
        public const string SetMoneyAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmMoneyAttribute.html";
        public const string SetOptionSetHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmOptionSet.html";
        public const string SetOptionSetAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmOptionSetAttribute.html";
        public const string SetOptionSetValueHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmOptionSetValue.html";
        public const string SetRelationshipHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmRelationship.html";
        public const string SetRelationshipCascadeConfigHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmRelationshipCascadeConfig.html";
        public const string SetStringAttributeHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmStringAttribute.html";
        public const string AddContentHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmContent.html";
        public const string GetContentHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmContent.html";
        public const string JoinContentHelpUrl = "http://crmpowershell.amsoftware.nl/Join-CrmContent.html";
        public const string RemoveContentHelpUrl = "http://crmpowershell.amsoftware.nl/Remove-CrmContent.html";
        public const string SetContentHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmContent.html";
        public const string SplitContentHelpUrl = "http://crmpowershell.amsoftware.nl/Split-CrmContent.html";
        public const string AddLanguageHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmLanguage.html";
        public const string ExportTranslationHelpUrl = "http://crmpowershell.amsoftware.nl/Export-CrmTranslation.html";
        public const string GetBusinessUnitHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmBusinessUnit.html";
        public const string GetLanguageHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmLanguage.html";
        public const string GetPrincipalRolesHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmPrincipalRoles.html";
        public const string GetProcessHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmProcess.html";
        public const string GetRoleHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmRole.html";
        public const string GetRolePrincipalsHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmRolePrincipals.html";
        public const string GetTeamHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmTeam.html";
        public const string GetTeamUsersHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmTeamUsers.html";
        public const string GetUserHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmUser.html";
        public const string GetUserTeamsHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmUserTeams.html";
        public const string ImportTranslationHelpUrl = "http://crmpowershell.amsoftware.nl/Import-CrmTranslation.html";
        public const string InvokeRequestHelpUrl = "http://crmpowershell.amsoftware.nl/Invoke-CrmRequest.html";
        public const string NewBusinessUnitHelpUrl = "http://crmpowershell.amsoftware.nl/New-CrmBusinessUnit.html";
        public const string NewRoleHelpUrl = "http://crmpowershell.amsoftware.nl/New-CrmRole.html";
        public const string NewTeamHelpUrl = "http://crmpowershell.amsoftware.nl/New-CrmTeam.html";
        public const string NewUserHelpUrl = "http://crmpowershell.amsoftware.nl/New-CrmUser.html";
        public const string RemoveLanguageHelpUrl = "http://crmpowershell.amsoftware.nl/Remove-CrmLanguage.html";
        public const string RemoveUserParentHelpUrl = "http://crmpowershell.amsoftware.nl/Remove-CrmUserParent.html";
        public const string SetOwnerHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmOwner.html";
        public const string SetPrincipalRolesHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmPrincipalRoles.html";
        public const string SetRolePrincipalsHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmRolePrincipals.html";
        public const string SetTeamUsersHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmTeamUsers.html";
        public const string SetUserTeamsHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmUserTeams.html";
        public const string StartProcessHelpUrl = "http://crmpowershell.amsoftware.nl/Start-CrmProcess.html";
        public const string StopProcessHelpUrl = "http://crmpowershell.amsoftware.nl/Stop-CrmProcess.html";
        public const string AddSolutionComponentHelpUrl = "http://crmpowershell.amsoftware.nl/Add-CrmSolutionComponent.html";
        public const string ExportSolutionHelpUrl = "http://crmpowershell.amsoftware.nl/Export-CrmSolution.html";
        public const string ExportWebresourceHelpUrl = "http://crmpowershell.amsoftware.nl/Export-CrmWebresource.html";
        public const string GetPublisherHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmPublisher.html";
        public const string GetSolutionHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmSolution.html";
        public const string GetSolutionComponentHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmSolutionComponent.html";
        public const string GetWebresourceHelpUrl = "http://crmpowershell.amsoftware.nl/Get-CrmWebresource.html";
        public const string ImportSolutionHelpUrl = "http://crmpowershell.amsoftware.nl/Import-CrmSolution.html";
        public const string ImportWebresourceHelpUrl = "http://crmpowershell.amsoftware.nl/Import-CrmWebresource.html";
        public const string NewPublisherHelpUrl = "http://crmpowershell.amsoftware.nl/New-CrmPublisher.html";
        public const string NewSolutionHelpUrl = "http://crmpowershell.amsoftware.nl/New-CrmSolution.html";
        public const string NewWebresourceHelpUrl = "http://crmpowershell.amsoftware.nl/New-CrmWebresource.html";
        public const string PublishComponentHelpUrl = "http://crmpowershell.amsoftware.nl/Publish-CrmComponent.html";
        public const string RemoveSolutionComponentHelpUrl = "http://crmpowershell.amsoftware.nl/Remove-CrmSolutionComponent.html";
        public const string RemoveWebresourceHelpUrl = "http://crmpowershell.amsoftware.nl/Remove-CrmWebresource.html";
        public const string SetWebresourceHelpUrl = "http://crmpowershell.amsoftware.nl/Set-CrmWebresource.html";
        public const string TestSolutionHelpUrl = "http://crmpowershell.amsoftware.nl/Test-CrmSolution.html";
        public const string TestSolutionComponentHelpUrl = "http://crmpowershell.amsoftware.nl/Test-CrmSolutionComponent.html";
        public const string UseSolutionHelpUrl = "http://crmpowershell.amsoftware.nl/Use-CrmSolution.html";
    }
}
